# Generated by Django 4.0.4 on 2022-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
